export default {
    id: "H28",
    name: '平成28年度',
    contents: [
        {
            title: "定演カレンダー",
            images: [
                require('~/assets/images/H28/concert_calender/1.jpg'),
                require('~/assets/images/H28/concert_calender/2.jpg'),
                require('~/assets/images/H28/concert_calender/3.jpg'),
                require('~/assets/images/H28/concert_calender/4.jpg'),
                require('~/assets/images/H28/concert_calender/5.jpg'),
                require('~/assets/images/H28/concert_calender/6.jpg'),
                require('~/assets/images/H28/concert_calender/7.jpg'),
                require('~/assets/images/H28/concert_calender/8.jpg'),
                require('~/assets/images/H28/concert_calender/9.jpg'),
                require('~/assets/images/H28/concert_calender/11.jpg'),
                require('~/assets/images/H28/concert_calender/12.jpg'),
                require('~/assets/images/H28/concert_calender/13.jpg'),
                require('~/assets/images/H28/concert_calender/14.jpg'),
                require('~/assets/images/H28/concert_calender/15.jpg'),
                require('~/assets/images/H28/concert_calender/16.jpg'),
                require('~/assets/images/H28/concert_calender/17.jpg'),
                require('~/assets/images/H28/concert_calender/18.jpg'),
                require('~/assets/images/H28/concert_calender/19.jpg'),
                require('~/assets/images/H28/concert_calender/20.jpg'),
                require('~/assets/images/H28/concert_calender/21.jpg'),
                require('~/assets/images/H28/concert_calender/22.jpg'),
                require('~/assets/images/H28/concert_calender/23.jpg'),
                require('~/assets/images/H28/concert_calender/24.jpg'),
                require('~/assets/images/H28/concert_calender/25.jpg'),
                require('~/assets/images/H28/concert_calender/26.jpg'),
                require('~/assets/images/H28/concert_calender/27.jpg'),
                require('~/assets/images/H28/concert_calender/28.jpg'),
                require('~/assets/images/H28/concert_calender/29.jpg'),
                require('~/assets/images/H28/concert_calender/30.jpg'),
            ],
        },
        {
            title: 'みんなの写真',
            images: [
                require('~/assets/images/H28/photos/italy.jpg'),
                require('~/assets/images/H28/photos/spring.jpg'),
                require('~/assets/images/H28/photos/sinkan1.jpg'),
                require('~/assets/images/H28/photos/sinkan2.jpg'),
                require('~/assets/images/H28/photos/sinkan3.jpg'),
                require('~/assets/images/H28/photos/sinkan4.jpg'),
                require('~/assets/images/H28/photos/obog1.jpg'),
                require('~/assets/images/H28/photos/sotsugyou.jpg'),
                require('~/assets/images/H28/photos/rensyuu.jpg'),
                require('~/assets/images/H28/photos/houmon.jpg'),
                require('~/assets/images/H28/photos/ken1.jpg'),
                require('~/assets/images/H28/photos/ken2.jpg'),
                require('~/assets/images/H28/photos/autumn2.jpg'),
                require('~/assets/images/H28/photos/autumn3.jpg'),
                require('~/assets/images/H28/photos/autumn4.jpg'),
                require('~/assets/images/H28/photos/obog2.jpg'),
                require('~/assets/images/H28/photos/kyushu1.jpg'),
                require('~/assets/images/H28/photos/kyushu2.jpg'),
                require('~/assets/images/H28/photos/zenkoku1.jpg'),
                require('~/assets/images/H28/photos/zenkoku2.jpg'),
                require('~/assets/images/H28/photos/zenkoku3.jpg'),
                require('~/assets/images/H28/photos/zenkoku4.jpg'),
                require('~/assets/images/H28/photos/radio.jpg'),
                require('~/assets/images/H28/photos/teien1.jpg'),
                require('~/assets/images/H28/photos/teien2.jpg'),
                require('~/assets/images/H28/photos/teien3.jpg'),
                require('~/assets/images/H28/photos/teien4.jpg'),
                require('~/assets/images/H28/photos/teien5.jpg'),
                require('~/assets/images/H28/photos/teien6.jpg'),
                require('~/assets/images/H28/photos/newonkei.jpg'),
            ],
        }
    ]
}