export default {
    id: "H29",
    name: '平成29年度',
    thumbnail: require('~/assets/images/H29/photos/teien.jpg'),
    dialog: false,
    contents: [
        {
            title: "定演カレンダー",
            images: [
                require('~/assets/images/H29/concert_calender/1.jpg'),
                require('~/assets/images/H29/concert_calender/2.jpg'),
                require('~/assets/images/H29/concert_calender/3.jpg'),
                require('~/assets/images/H29/concert_calender/4.jpg'),
                require('~/assets/images/H29/concert_calender/5.jpg'),
                require('~/assets/images/H29/concert_calender/6.jpg'),
                require('~/assets/images/H29/concert_calender/7.jpg'),
                require('~/assets/images/H29/concert_calender/8.jpg'),
                require('~/assets/images/H29/concert_calender/9.jpg'),
                require('~/assets/images/H29/concert_calender/11.jpg'),
                require('~/assets/images/H29/concert_calender/12.jpg'),
                require('~/assets/images/H29/concert_calender/13.jpg'),
                require('~/assets/images/H29/concert_calender/14.jpg'),
                require('~/assets/images/H29/concert_calender/15.jpg'),
                require('~/assets/images/H29/concert_calender/16.jpg'),
                require('~/assets/images/H29/concert_calender/17.jpg'),
                require('~/assets/images/H29/concert_calender/18.jpg'),
                require('~/assets/images/H29/concert_calender/19.jpg'),
                require('~/assets/images/H29/concert_calender/20.jpg'),
                require('~/assets/images/H29/concert_calender/21.jpg'),
                require('~/assets/images/H29/concert_calender/22.jpg'),
                require('~/assets/images/H29/concert_calender/23.jpg'),
                require('~/assets/images/H29/concert_calender/24.jpg'),
                require('~/assets/images/H29/concert_calender/25.jpg'),
                require('~/assets/images/H29/concert_calender/26.jpg'),
                require('~/assets/images/H29/concert_calender/27.jpg'),
                require('~/assets/images/H29/concert_calender/28.jpg'),
                require('~/assets/images/H29/concert_calender/29.jpg'),
                require('~/assets/images/H29/concert_calender/30.jpg'),
            ],
            index: null
        },
        {
            title: 'みんなの写真',
            images: [
                require('~/assets/images/H29/photos/spring1.jpg'),
                require('~/assets/images/H29/photos/spring2.jpg'),
                require('~/assets/images/H29/photos/springgroup1.jpg'),
                require('~/assets/images/H29/photos/springgroup2.jpg'),
                require('~/assets/images/H29/photos/sinkan1.jpg'),
                require('~/assets/images/H29/photos/sinkan2.jpg'),
                require('~/assets/images/H29/photos/sinkan3.jpg'),
                require('~/assets/images/H29/photos/sinkan4.jpg'),
                require('~/assets/images/H29/photos/sinkan5.jpg'),
                require('~/assets/images/H29/photos/obog.jpg'),
                require('~/assets/images/H29/photos/summer1.jpg'),
                require('~/assets/images/H29/photos/summer2.jpg'),
                require('~/assets/images/H29/photos/summer3.jpg'),
                require('~/assets/images/H29/photos/joikon1.jpg'),
                require('~/assets/images/H29/photos/joikon2.jpg'),
                require('~/assets/images/H29/photos/joikon3.jpg'),
                require('~/assets/images/H29/photos/withnobunaga.jpg'),
                require('~/assets/images/H29/photos/autumn1.jpg'),
                require('~/assets/images/H29/photos/autumn2.jpg'),
                require('~/assets/images/H29/photos/autumn3.jpg'),
                require('~/assets/images/H29/photos/kyusyu1.jpg'),
                require('~/assets/images/H29/photos/zenkoku2.jpg'),
                require('~/assets/images/H29/photos/zenkoku4.jpg'),
                require('~/assets/images/H29/photos/zenkoku5.jpg'),
                require('~/assets/images/H29/photos/teien.jpg'),
                require('~/assets/images/H29/photos/newonkei.jpg'),
            ],
            index: null
        }
    ]

}